# Generated by Django 2.2.12 on 2020-04-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='snippet',
            index=models.Index(fields=['created'], name='snippets_sn_created_aac5d4_idx'),
        ),
    ]
